/* Generated by regenerate.sh -- do not edit. */
#include "ndk-stub-runtime.h"

struct atl_ndk_stub atl_ndk_stub_table[] = {
  { "AChoreographerFrameCallbackData_getFrameTimelineDeadlineNanos", 0 },
  { "AChoreographerFrameCallbackData_getFrameTimelineExpectedPresentationTimeNanos", 0 },
  { "AChoreographerFrameCallbackData_getFrameTimelinesLength", 0 },
  { "AChoreographerFrameCallbackData_getFrameTimelineVsyncId", 0 },
  { "AChoreographerFrameCallbackData_getFrameTimeNanos", 0 },
  { "AChoreographerFrameCallbackData_getPreferredFrameTimelineIndex", 0 },
  { "AChoreographer_getInstance", 0 },
  { "AChoreographer_postFrameCallback", 0 },
  { "AChoreographer_postFrameCallback64", 0 },
  { "AChoreographer_postFrameCallbackDelayed", 0 },
  { "AChoreographer_postFrameCallbackDelayed64", 0 },
  { "AChoreographer_postVsyncCallback", 0 },
  { "AChoreographer_registerRefreshRateCallback", 0 },
  { "AChoreographer_unregisterRefreshRateCallback", 0 },
  { "AFont_close", 0 },
  { "AFont_getAxisCount", 0 },
  { "AFont_getAxisTag", 0 },
  { "AFont_getAxisValue", 0 },
  { "AFont_getCollectionIndex", 0 },
  { "AFont_getFontFilePath", 0 },
  { "AFont_getLocale", 0 },
  { "AFont_getWeight", 0 },
  { "AFont_isItalic", 0 },
  { "AFontMatcher_create", 0 },
  { "AFontMatcher_destroy", 0 },
  { "AFontMatcher_match", 0 },
  { "AFontMatcher_setFamilyVariant", 0 },
  { "AFontMatcher_setLocales", 0 },
  { "AFontMatcher_setStyle", 0 },
  { "AHardwareBuffer_acquire", 0 },
  { "AHardwareBuffer_allocate", 0 },
  { "AHardwareBuffer_describe", 0 },
  { "AHardwareBuffer_isSupported", 0 },
  { "AHardwareBuffer_lock", 0 },
  { "AHardwareBuffer_lockAndGetInfo", 0 },
  { "AHardwareBuffer_lockPlanes", 0 },
  { "AHardwareBuffer_recvHandleFromUnixSocket", 0 },
  { "AHardwareBuffer_release", 0 },
  { "AHardwareBuffer_sendHandleToUnixSocket", 0 },
  { "AHardwareBuffer_unlock", 0 },
  { "AImageDecoder_advanceFrame", 0 },
  { "AImageDecoder_computeSampledSize", 0 },
  { "AImageDecoder_createFromAAsset", 0 },
  { "AImageDecoder_createFromBuffer", 0 },
  { "AImageDecoder_createFromFd", 0 },
  { "AImageDecoder_decodeImage", 0 },
  { "AImageDecoder_delete", 0 },
  { "AImageDecoderFrameInfo_create", 0 },
  { "AImageDecoderFrameInfo_delete", 0 },
  { "AImageDecoderFrameInfo_getBlendOp", 0 },
  { "AImageDecoderFrameInfo_getDisposeOp", 0 },
  { "AImageDecoderFrameInfo_getDuration", 0 },
  { "AImageDecoderFrameInfo_getFrameRect", 0 },
  { "AImageDecoderFrameInfo_hasAlphaWithinBounds", 0 },
  { "AImageDecoder_getFrameInfo", 0 },
  { "AImageDecoder_getHeaderInfo", 0 },
  { "AImageDecoder_getMinimumStride", 0 },
  { "AImageDecoder_getRepeatCount", 0 },
  { "AImageDecoderHeaderInfo_getAlphaFlags", 0 },
  { "AImageDecoderHeaderInfo_getAndroidBitmapFormat", 0 },
  { "AImageDecoderHeaderInfo_getDataSpace", 0 },
  { "AImageDecoderHeaderInfo_getHeight", 0 },
  { "AImageDecoderHeaderInfo_getMimeType", 0 },
  { "AImageDecoderHeaderInfo_getWidth", 0 },
  { "AImageDecoder_isAnimated", 0 },
  { "AImageDecoder_resultToString", 0 },
  { "AImageDecoder_rewind", 0 },
  { "AImageDecoder_setAndroidBitmapFormat", 0 },
  { "AImageDecoder_setCrop", 0 },
  { "AImageDecoder_setDataSpace", 0 },
  { "AImageDecoder_setInternallyHandleDisposePrevious", 0 },
  { "AImageDecoder_setTargetSize", 0 },
  { "AImageDecoder_setUnpremultipliedRequired", 0 },
  { "AImage_delete", 0 },
  { "AImage_deleteAsync", 0 },
  { "AImage_getCropRect", 0 },
  { "AImage_getDataSpace", 0 },
  { "AImage_getFormat", 0 },
  { "AImage_getHardwareBuffer", 0 },
  { "AImage_getHeight", 0 },
  { "AImage_getNumberOfPlanes", 0 },
  { "AImage_getPlaneData", 0 },
  { "AImage_getPlanePixelStride", 0 },
  { "AImage_getPlaneRowStride", 0 },
  { "AImage_getTimestamp", 0 },
  { "AImage_getWidth", 0 },
  { "AImageReader_acquireLatestImage", 0 },
  { "AImageReader_acquireLatestImageAsync", 0 },
  { "AImageReader_acquireNextImage", 0 },
  { "AImageReader_acquireNextImageAsync", 0 },
  { "AImageReader_delete", 0 },
  { "AImageReader_getFormat", 0 },
  { "AImageReader_getHeight", 0 },
  { "AImageReader_getMaxImages", 0 },
  { "AImageReader_getWidth", 0 },
  { "AImageReader_getWindow", 0 },
  { "AImageReader_getWindowNativeHandle", 0 },
  { "AImageReader_new", 0 },
  { "AImageReader_newWithDataSpace", 0 },
  { "AImageReader_newWithUsage", 0 },
  { "AImageReader_setBufferRemovedListener", 0 },
  { "AImageReader_setImageListener", 0 },
  { "AInputEvent_getDeviceId", 0 },
  { "AInputEvent_release", 0 },
  { "AInputQueue_fromJava", 0 },
  { "AInputQueue_get_event", 0 },
  { "AInputQueue_hasEvents", 0 },
  { "AKeyEvent_fromJava", 0 },
  { "AKeyEvent_getAction", 0 },
  { "AKeyEvent_getDownTime", 0 },
  { "AKeyEvent_getEventTime", 0 },
  { "AKeyEvent_getFlags", 0 },
  { "AKeyEvent_getMetaState", 0 },
  { "AKeyEvent_getRepeatCount", 0 },
  { "AKeyEvent_getScanCode", 0 },
  { "AMediaCodecActionCode_isRecoverable", 0 },
  { "AMediaCodecActionCode_isTransient", 0 },
  { "AMediaCodec_getBufferFormat", 0 },
  { "AMediaCodec_getInputBuffers", 0 },
  { "AMediaCodec_getInputFormat", 0 },
  { "AMediaCodec_getName", 0 },
  { "AMediaCodec_getOutputBuffers", 0 },
  { "AMediaCodec_releaseCrypto", 0 },
  { "AMediaCodec_releaseName", 0 },
  { "AMediaCodec_setAsyncNotifyCallback", 0 },
  { "AMediaCodec_setOnFrameRenderedCallback", 0 },
  { "AMediaCrypto_delete", 0 },
  { "AMediaCrypto_isCryptoSchemeSupported", 0 },
  { "AMediaCrypto_new", 0 },
  { "AMediaCrypto_requiresSecureDecoderComponent", 0 },
  { "AMediaDataSource_close", 0 },
  { "AMediaDataSource_delete", 0 },
  { "AMediaDataSource_new", 0 },
  { "AMediaDataSource_newUri", 0 },
  { "AMediaDataSource_setClose", 0 },
  { "AMediaDataSource_setGetAvailableSize", 0 },
  { "AMediaDataSource_setGetSize", 0 },
  { "AMediaDataSource_setReadAt", 0 },
  { "AMediaDataSource_setUserdata", 0 },
  { "AMediaDrm_closeSession", 0 },
  { "AMediaDrm_createByUUID", 0 },
  { "AMediaDrm_decrypt", 0 },
  { "AMediaDrm_encrypt", 0 },
  { "AMediaDrm_getKeyRequest", 0 },
  { "AMediaDrm_getKeyRequestWithDefaultUrlAndType", 0 },
  { "AMediaDrm_getPropertyByteArray", 0 },
  { "AMediaDrm_getPropertyString", 0 },
  { "AMediaDrm_getProvisionRequest", 0 },
  { "AMediaDrm_getSecureStops", 0 },
  { "AMediaDrm_isCryptoSchemeSupported", 0 },
  { "AMediaDrm_openSession", 0 },
  { "AMediaDrm_provideKeyResponse", 0 },
  { "AMediaDrm_provideProvisionResponse", 0 },
  { "AMediaDrm_queryKeyStatus", 0 },
  { "AMediaDrm_release", 0 },
  { "AMediaDrm_releaseSecureStops", 0 },
  { "AMediaDrm_removeKeys", 0 },
  { "AMediaDrm_restoreKeys", 0 },
  { "AMediaDrm_setOnEventListener", 0 },
  { "AMediaDrm_setOnExpirationUpdateListener", 0 },
  { "AMediaDrm_setOnKeysChangeListener", 0 },
  { "AMediaDrm_setPropertyByteArray", 0 },
  { "AMediaDrm_setPropertyString", 0 },
  { "AMediaDrm_sign", 0 },
  { "AMediaDrm_verify", 0 },
  { "AMediaExtractor_advance", 0 },
  { "AMediaExtractor_delete", 0 },
  { "AMediaExtractor_getCachedDuration", 0 },
  { "AMediaExtractor_getFileFormat", 0 },
  { "AMediaExtractor_getPsshInfo", 0 },
  { "AMediaExtractor_getSampleCryptoInfo", 0 },
  { "AMediaExtractor_getSampleFlags", 0 },
  { "AMediaExtractor_getSampleFormat", 0 },
  { "AMediaExtractor_getSampleSize", 0 },
  { "AMediaExtractor_getSampleTime", 0 },
  { "AMediaExtractor_getSampleTrackIndex", 0 },
  { "AMediaExtractor_getTrackCount", 0 },
  { "AMediaExtractor_getTrackFormat", 0 },
  { "AMediaExtractor_new", 0 },
  { "AMediaExtractor_readSampleData", 0 },
  { "AMediaExtractor_seekTo", 0 },
  { "AMediaExtractor_selectTrack", 0 },
  { "AMediaExtractor_setDataSource", 0 },
  { "AMediaExtractor_setDataSourceCustom", 0 },
  { "AMediaExtractor_setDataSourceFd", 0 },
  { "AMediaExtractor_unselectTrack", 0 },
  { "AMediaFormat_clear", 0 },
  { "AMediaFormat_copy", 0 },
  { "AMediaFormat_getDouble", 0 },
  { "AMediaFormat_getRect", 0 },
  { "AMediaFormat_getSize", 0 },
  { "AMediaFormat_setDouble", 0 },
  { "AMediaFormat_setRect", 0 },
  { "AMediaFormat_setSize", 0 },
  { "AMediaMuxer_addTrack", 0 },
  { "AMediaMuxer_append", 0 },
  { "AMediaMuxer_delete", 0 },
  { "AMediaMuxer_getTrackCount", 0 },
  { "AMediaMuxer_getTrackFormat", 0 },
  { "AMediaMuxer_new", 0 },
  { "AMediaMuxer_setLocation", 0 },
  { "AMediaMuxer_setOrientationHint", 0 },
  { "AMediaMuxer_start", 0 },
  { "AMediaMuxer_stop", 0 },
  { "AMediaMuxer_writeSampleData", 0 },
  { "AMotionEvent_fromJava", 0 },
  { "AMotionEvent_getActionButton", 0 },
  { "AMotionEvent_getButtonState", 0 },
  { "AMotionEvent_getClassification", 0 },
  { "AMotionEvent_getDownTime", 0 },
  { "AMotionEvent_getEdgeFlags", 0 },
  { "AMotionEvent_getEventTime", 0 },
  { "AMotionEvent_getFlags", 0 },
  { "AMotionEvent_getHistoricalAxisValue", 0 },
  { "AMotionEvent_getHistoricalEventTime", 0 },
  { "AMotionEvent_getHistoricalOrientation", 0 },
  { "AMotionEvent_getHistoricalPressure", 0 },
  { "AMotionEvent_getHistoricalRawX", 0 },
  { "AMotionEvent_getHistoricalRawY", 0 },
  { "AMotionEvent_getHistoricalSize", 0 },
  { "AMotionEvent_getHistoricalToolMajor", 0 },
  { "AMotionEvent_getHistoricalToolMinor", 0 },
  { "AMotionEvent_getHistoricalTouchMajor", 0 },
  { "AMotionEvent_getHistoricalTouchMinor", 0 },
  { "AMotionEvent_getHistoricalX", 0 },
  { "AMotionEvent_getHistoricalY", 0 },
  { "AMotionEvent_getHistorySize", 0 },
  { "AMotionEvent_getMetaState", 0 },
  { "AMotionEvent_getOrientation", 0 },
  { "AMotionEvent_getPressure", 0 },
  { "AMotionEvent_getRawX", 0 },
  { "AMotionEvent_getRawY", 0 },
  { "AMotionEvent_getSize", 0 },
  { "AMotionEvent_getToolMajor", 0 },
  { "AMotionEvent_getToolMinor", 0 },
  { "AMotionEvent_getToolType", 0 },
  { "AMotionEvent_getTouchMajor", 0 },
  { "AMotionEvent_getTouchMinor", 0 },
  { "AMotionEvent_getXOffset", 0 },
  { "AMotionEvent_getXPrecision", 0 },
  { "AMotionEvent_getYOffset", 0 },
  { "AMotionEvent_getYPrecision", 0 },
  { "ANativeWindow_getBuffersDataSpace", 0 },
  { "ANativeWindow_setBuffersDataSpace", 0 },
  { "ANativeWindow_toSurface", 0 },
  { "ANativeWindow_tryAllocateBuffers", 0 },
  { "AndroidBitmap_compress", 0 },
  { "AndroidBitmap_getDataSpace", 0 },
  { "AndroidBitmap_getHardwareBuffer", 0 },
  { "APerformanceHint_closeSession", 0 },
  { "APerformanceHint_createSession", 0 },
  { "APerformanceHint_getManager", 0 },
  { "APerformanceHint_getPreferredUpdateRateNanos", 0 },
  { "APerformanceHint_reportActualWorkDuration", 0 },
  { "APerformanceHint_updateTargetWorkDuration", 0 },
  { "ASharedMemory_create", 0 },
  { "ASharedMemory_getSize", 0 },
  { "ASharedMemory_setProt", 0 },
  { "ASurfaceTexture_acquireANativeWindow", 0 },
  { "ASurfaceTexture_attachToGLContext", 0 },
  { "ASurfaceTexture_detachFromGLContext", 0 },
  { "ASurfaceTexture_fromSurfaceTexture", 0 },
  { "ASurfaceTexture_getTimestamp", 0 },
  { "ASurfaceTexture_getTransformMatrix", 0 },
  { "ASurfaceTexture_release", 0 },
  { "ASurfaceTexture_updateTexImage", 0 },
  { "ASystemFont_close", 0 },
  { "ASystemFont_getAxisCount", 0 },
  { "ASystemFont_getAxisTag", 0 },
  { "ASystemFont_getAxisValue", 0 },
  { "ASystemFont_getCollectionINdex", 0 },
  { "ASystemFont_getFontFilePath", 0 },
  { "ASystemFont_getLocale", 0 },
  { "ASystemFont_getWeight", 0 },
  { "ASystemFont_isItalic", 0 },
  { "ASystemFontIterator_close", 0 },
  { "ASystemFontIterator_next", 0 },
  { "ASystemFontIterator_open", 0 },
  { "ATrace_beginAsyncSection", 0 },
  { "ATrace_beginSection", 0 },
  { "ATrace_endAsyncSection", 0 },
  { "ATrace_endSection", 0 },
  { "ATrace_setCounter", 0 },
};
const unsigned atl_ndk_stub_count =
    sizeof(atl_ndk_stub_table) / sizeof(atl_ndk_stub_table[0]);

void AChoreographerFrameCallbackData_getFrameTimelineDeadlineNanos(void) { ATL_NDK_STUB_BODY(0); }
void AChoreographerFrameCallbackData_getFrameTimelineExpectedPresentationTimeNanos(void) { ATL_NDK_STUB_BODY(1); }
void AChoreographerFrameCallbackData_getFrameTimelinesLength(void) { ATL_NDK_STUB_BODY(2); }
void AChoreographerFrameCallbackData_getFrameTimelineVsyncId(void) { ATL_NDK_STUB_BODY(3); }
void AChoreographerFrameCallbackData_getFrameTimeNanos(void) { ATL_NDK_STUB_BODY(4); }
void AChoreographerFrameCallbackData_getPreferredFrameTimelineIndex(void) { ATL_NDK_STUB_BODY(5); }
void AChoreographer_getInstance(void) { ATL_NDK_STUB_BODY(6); }
void AChoreographer_postFrameCallback(void) { ATL_NDK_STUB_BODY(7); }
void AChoreographer_postFrameCallback64(void) { ATL_NDK_STUB_BODY(8); }
void AChoreographer_postFrameCallbackDelayed(void) { ATL_NDK_STUB_BODY(9); }
void AChoreographer_postFrameCallbackDelayed64(void) { ATL_NDK_STUB_BODY(10); }
void AChoreographer_postVsyncCallback(void) { ATL_NDK_STUB_BODY(11); }
void AChoreographer_registerRefreshRateCallback(void) { ATL_NDK_STUB_BODY(12); }
void AChoreographer_unregisterRefreshRateCallback(void) { ATL_NDK_STUB_BODY(13); }
void AFont_close(void) { ATL_NDK_STUB_BODY(14); }
void AFont_getAxisCount(void) { ATL_NDK_STUB_BODY(15); }
void AFont_getAxisTag(void) { ATL_NDK_STUB_BODY(16); }
void AFont_getAxisValue(void) { ATL_NDK_STUB_BODY(17); }
void AFont_getCollectionIndex(void) { ATL_NDK_STUB_BODY(18); }
void AFont_getFontFilePath(void) { ATL_NDK_STUB_BODY(19); }
void AFont_getLocale(void) { ATL_NDK_STUB_BODY(20); }
void AFont_getWeight(void) { ATL_NDK_STUB_BODY(21); }
void AFont_isItalic(void) { ATL_NDK_STUB_BODY(22); }
void AFontMatcher_create(void) { ATL_NDK_STUB_BODY(23); }
void AFontMatcher_destroy(void) { ATL_NDK_STUB_BODY(24); }
void AFontMatcher_match(void) { ATL_NDK_STUB_BODY(25); }
void AFontMatcher_setFamilyVariant(void) { ATL_NDK_STUB_BODY(26); }
void AFontMatcher_setLocales(void) { ATL_NDK_STUB_BODY(27); }
void AFontMatcher_setStyle(void) { ATL_NDK_STUB_BODY(28); }
void AHardwareBuffer_acquire(void) { ATL_NDK_STUB_BODY(29); }
void AHardwareBuffer_allocate(void) { ATL_NDK_STUB_BODY(30); }
void AHardwareBuffer_describe(void) { ATL_NDK_STUB_BODY(31); }
void AHardwareBuffer_isSupported(void) { ATL_NDK_STUB_BODY(32); }
void AHardwareBuffer_lock(void) { ATL_NDK_STUB_BODY(33); }
void AHardwareBuffer_lockAndGetInfo(void) { ATL_NDK_STUB_BODY(34); }
void AHardwareBuffer_lockPlanes(void) { ATL_NDK_STUB_BODY(35); }
void AHardwareBuffer_recvHandleFromUnixSocket(void) { ATL_NDK_STUB_BODY(36); }
void AHardwareBuffer_release(void) { ATL_NDK_STUB_BODY(37); }
void AHardwareBuffer_sendHandleToUnixSocket(void) { ATL_NDK_STUB_BODY(38); }
void AHardwareBuffer_unlock(void) { ATL_NDK_STUB_BODY(39); }
void AImageDecoder_advanceFrame(void) { ATL_NDK_STUB_BODY(40); }
void AImageDecoder_computeSampledSize(void) { ATL_NDK_STUB_BODY(41); }
void AImageDecoder_createFromAAsset(void) { ATL_NDK_STUB_BODY(42); }
void AImageDecoder_createFromBuffer(void) { ATL_NDK_STUB_BODY(43); }
void AImageDecoder_createFromFd(void) { ATL_NDK_STUB_BODY(44); }
void AImageDecoder_decodeImage(void) { ATL_NDK_STUB_BODY(45); }
void AImageDecoder_delete(void) { ATL_NDK_STUB_BODY(46); }
void AImageDecoderFrameInfo_create(void) { ATL_NDK_STUB_BODY(47); }
void AImageDecoderFrameInfo_delete(void) { ATL_NDK_STUB_BODY(48); }
void AImageDecoderFrameInfo_getBlendOp(void) { ATL_NDK_STUB_BODY(49); }
void AImageDecoderFrameInfo_getDisposeOp(void) { ATL_NDK_STUB_BODY(50); }
void AImageDecoderFrameInfo_getDuration(void) { ATL_NDK_STUB_BODY(51); }
void AImageDecoderFrameInfo_getFrameRect(void) { ATL_NDK_STUB_BODY(52); }
void AImageDecoderFrameInfo_hasAlphaWithinBounds(void) { ATL_NDK_STUB_BODY(53); }
void AImageDecoder_getFrameInfo(void) { ATL_NDK_STUB_BODY(54); }
void AImageDecoder_getHeaderInfo(void) { ATL_NDK_STUB_BODY(55); }
void AImageDecoder_getMinimumStride(void) { ATL_NDK_STUB_BODY(56); }
void AImageDecoder_getRepeatCount(void) { ATL_NDK_STUB_BODY(57); }
void AImageDecoderHeaderInfo_getAlphaFlags(void) { ATL_NDK_STUB_BODY(58); }
void AImageDecoderHeaderInfo_getAndroidBitmapFormat(void) { ATL_NDK_STUB_BODY(59); }
void AImageDecoderHeaderInfo_getDataSpace(void) { ATL_NDK_STUB_BODY(60); }
void AImageDecoderHeaderInfo_getHeight(void) { ATL_NDK_STUB_BODY(61); }
void AImageDecoderHeaderInfo_getMimeType(void) { ATL_NDK_STUB_BODY(62); }
void AImageDecoderHeaderInfo_getWidth(void) { ATL_NDK_STUB_BODY(63); }
void AImageDecoder_isAnimated(void) { ATL_NDK_STUB_BODY(64); }
void AImageDecoder_resultToString(void) { ATL_NDK_STUB_BODY(65); }
void AImageDecoder_rewind(void) { ATL_NDK_STUB_BODY(66); }
void AImageDecoder_setAndroidBitmapFormat(void) { ATL_NDK_STUB_BODY(67); }
void AImageDecoder_setCrop(void) { ATL_NDK_STUB_BODY(68); }
void AImageDecoder_setDataSpace(void) { ATL_NDK_STUB_BODY(69); }
void AImageDecoder_setInternallyHandleDisposePrevious(void) { ATL_NDK_STUB_BODY(70); }
void AImageDecoder_setTargetSize(void) { ATL_NDK_STUB_BODY(71); }
void AImageDecoder_setUnpremultipliedRequired(void) { ATL_NDK_STUB_BODY(72); }
void AImage_delete(void) { ATL_NDK_STUB_BODY(73); }
void AImage_deleteAsync(void) { ATL_NDK_STUB_BODY(74); }
void AImage_getCropRect(void) { ATL_NDK_STUB_BODY(75); }
void AImage_getDataSpace(void) { ATL_NDK_STUB_BODY(76); }
void AImage_getFormat(void) { ATL_NDK_STUB_BODY(77); }
void AImage_getHardwareBuffer(void) { ATL_NDK_STUB_BODY(78); }
void AImage_getHeight(void) { ATL_NDK_STUB_BODY(79); }
void AImage_getNumberOfPlanes(void) { ATL_NDK_STUB_BODY(80); }
void AImage_getPlaneData(void) { ATL_NDK_STUB_BODY(81); }
void AImage_getPlanePixelStride(void) { ATL_NDK_STUB_BODY(82); }
void AImage_getPlaneRowStride(void) { ATL_NDK_STUB_BODY(83); }
void AImage_getTimestamp(void) { ATL_NDK_STUB_BODY(84); }
void AImage_getWidth(void) { ATL_NDK_STUB_BODY(85); }
void AImageReader_acquireLatestImage(void) { ATL_NDK_STUB_BODY(86); }
void AImageReader_acquireLatestImageAsync(void) { ATL_NDK_STUB_BODY(87); }
void AImageReader_acquireNextImage(void) { ATL_NDK_STUB_BODY(88); }
void AImageReader_acquireNextImageAsync(void) { ATL_NDK_STUB_BODY(89); }
void AImageReader_delete(void) { ATL_NDK_STUB_BODY(90); }
void AImageReader_getFormat(void) { ATL_NDK_STUB_BODY(91); }
void AImageReader_getHeight(void) { ATL_NDK_STUB_BODY(92); }
void AImageReader_getMaxImages(void) { ATL_NDK_STUB_BODY(93); }
void AImageReader_getWidth(void) { ATL_NDK_STUB_BODY(94); }
void AImageReader_getWindow(void) { ATL_NDK_STUB_BODY(95); }
void AImageReader_getWindowNativeHandle(void) { ATL_NDK_STUB_BODY(96); }
void AImageReader_new(void) { ATL_NDK_STUB_BODY(97); }
void AImageReader_newWithDataSpace(void) { ATL_NDK_STUB_BODY(98); }
void AImageReader_newWithUsage(void) { ATL_NDK_STUB_BODY(99); }
void AImageReader_setBufferRemovedListener(void) { ATL_NDK_STUB_BODY(100); }
void AImageReader_setImageListener(void) { ATL_NDK_STUB_BODY(101); }
void AInputEvent_getDeviceId(void) { ATL_NDK_STUB_BODY(102); }
void AInputEvent_release(void) { ATL_NDK_STUB_BODY(103); }
void AInputQueue_fromJava(void) { ATL_NDK_STUB_BODY(104); }
void AInputQueue_get_event(void) { ATL_NDK_STUB_BODY(105); }
void AInputQueue_hasEvents(void) { ATL_NDK_STUB_BODY(106); }
void AKeyEvent_fromJava(void) { ATL_NDK_STUB_BODY(107); }
void AKeyEvent_getAction(void) { ATL_NDK_STUB_BODY(108); }
void AKeyEvent_getDownTime(void) { ATL_NDK_STUB_BODY(109); }
void AKeyEvent_getEventTime(void) { ATL_NDK_STUB_BODY(110); }
void AKeyEvent_getFlags(void) { ATL_NDK_STUB_BODY(111); }
void AKeyEvent_getMetaState(void) { ATL_NDK_STUB_BODY(112); }
void AKeyEvent_getRepeatCount(void) { ATL_NDK_STUB_BODY(113); }
void AKeyEvent_getScanCode(void) { ATL_NDK_STUB_BODY(114); }
void AMediaCodecActionCode_isRecoverable(void) { ATL_NDK_STUB_BODY(115); }
void AMediaCodecActionCode_isTransient(void) { ATL_NDK_STUB_BODY(116); }
void AMediaCodec_getBufferFormat(void) { ATL_NDK_STUB_BODY(117); }
void AMediaCodec_getInputBuffers(void) { ATL_NDK_STUB_BODY(118); }
void AMediaCodec_getInputFormat(void) { ATL_NDK_STUB_BODY(119); }
void AMediaCodec_getName(void) { ATL_NDK_STUB_BODY(120); }
void AMediaCodec_getOutputBuffers(void) { ATL_NDK_STUB_BODY(121); }
void AMediaCodec_releaseCrypto(void) { ATL_NDK_STUB_BODY(122); }
void AMediaCodec_releaseName(void) { ATL_NDK_STUB_BODY(123); }
void AMediaCodec_setAsyncNotifyCallback(void) { ATL_NDK_STUB_BODY(124); }
void AMediaCodec_setOnFrameRenderedCallback(void) { ATL_NDK_STUB_BODY(125); }
void AMediaCrypto_delete(void) { ATL_NDK_STUB_BODY(126); }
void AMediaCrypto_isCryptoSchemeSupported(void) { ATL_NDK_STUB_BODY(127); }
void AMediaCrypto_new(void) { ATL_NDK_STUB_BODY(128); }
void AMediaCrypto_requiresSecureDecoderComponent(void) { ATL_NDK_STUB_BODY(129); }
void AMediaDataSource_close(void) { ATL_NDK_STUB_BODY(130); }
void AMediaDataSource_delete(void) { ATL_NDK_STUB_BODY(131); }
void AMediaDataSource_new(void) { ATL_NDK_STUB_BODY(132); }
void AMediaDataSource_newUri(void) { ATL_NDK_STUB_BODY(133); }
void AMediaDataSource_setClose(void) { ATL_NDK_STUB_BODY(134); }
void AMediaDataSource_setGetAvailableSize(void) { ATL_NDK_STUB_BODY(135); }
void AMediaDataSource_setGetSize(void) { ATL_NDK_STUB_BODY(136); }
void AMediaDataSource_setReadAt(void) { ATL_NDK_STUB_BODY(137); }
void AMediaDataSource_setUserdata(void) { ATL_NDK_STUB_BODY(138); }
void AMediaDrm_closeSession(void) { ATL_NDK_STUB_BODY(139); }
void AMediaDrm_createByUUID(void) { ATL_NDK_STUB_BODY(140); }
void AMediaDrm_decrypt(void) { ATL_NDK_STUB_BODY(141); }
void AMediaDrm_encrypt(void) { ATL_NDK_STUB_BODY(142); }
void AMediaDrm_getKeyRequest(void) { ATL_NDK_STUB_BODY(143); }
void AMediaDrm_getKeyRequestWithDefaultUrlAndType(void) { ATL_NDK_STUB_BODY(144); }
void AMediaDrm_getPropertyByteArray(void) { ATL_NDK_STUB_BODY(145); }
void AMediaDrm_getPropertyString(void) { ATL_NDK_STUB_BODY(146); }
void AMediaDrm_getProvisionRequest(void) { ATL_NDK_STUB_BODY(147); }
void AMediaDrm_getSecureStops(void) { ATL_NDK_STUB_BODY(148); }
void AMediaDrm_isCryptoSchemeSupported(void) { ATL_NDK_STUB_BODY(149); }
void AMediaDrm_openSession(void) { ATL_NDK_STUB_BODY(150); }
void AMediaDrm_provideKeyResponse(void) { ATL_NDK_STUB_BODY(151); }
void AMediaDrm_provideProvisionResponse(void) { ATL_NDK_STUB_BODY(152); }
void AMediaDrm_queryKeyStatus(void) { ATL_NDK_STUB_BODY(153); }
void AMediaDrm_release(void) { ATL_NDK_STUB_BODY(154); }
void AMediaDrm_releaseSecureStops(void) { ATL_NDK_STUB_BODY(155); }
void AMediaDrm_removeKeys(void) { ATL_NDK_STUB_BODY(156); }
void AMediaDrm_restoreKeys(void) { ATL_NDK_STUB_BODY(157); }
void AMediaDrm_setOnEventListener(void) { ATL_NDK_STUB_BODY(158); }
void AMediaDrm_setOnExpirationUpdateListener(void) { ATL_NDK_STUB_BODY(159); }
void AMediaDrm_setOnKeysChangeListener(void) { ATL_NDK_STUB_BODY(160); }
void AMediaDrm_setPropertyByteArray(void) { ATL_NDK_STUB_BODY(161); }
void AMediaDrm_setPropertyString(void) { ATL_NDK_STUB_BODY(162); }
void AMediaDrm_sign(void) { ATL_NDK_STUB_BODY(163); }
void AMediaDrm_verify(void) { ATL_NDK_STUB_BODY(164); }
void AMediaExtractor_advance(void) { ATL_NDK_STUB_BODY(165); }
void AMediaExtractor_delete(void) { ATL_NDK_STUB_BODY(166); }
void AMediaExtractor_getCachedDuration(void) { ATL_NDK_STUB_BODY(167); }
void AMediaExtractor_getFileFormat(void) { ATL_NDK_STUB_BODY(168); }
void AMediaExtractor_getPsshInfo(void) { ATL_NDK_STUB_BODY(169); }
void AMediaExtractor_getSampleCryptoInfo(void) { ATL_NDK_STUB_BODY(170); }
void AMediaExtractor_getSampleFlags(void) { ATL_NDK_STUB_BODY(171); }
void AMediaExtractor_getSampleFormat(void) { ATL_NDK_STUB_BODY(172); }
void AMediaExtractor_getSampleSize(void) { ATL_NDK_STUB_BODY(173); }
void AMediaExtractor_getSampleTime(void) { ATL_NDK_STUB_BODY(174); }
void AMediaExtractor_getSampleTrackIndex(void) { ATL_NDK_STUB_BODY(175); }
void AMediaExtractor_getTrackCount(void) { ATL_NDK_STUB_BODY(176); }
void AMediaExtractor_getTrackFormat(void) { ATL_NDK_STUB_BODY(177); }
void AMediaExtractor_new(void) { ATL_NDK_STUB_BODY(178); }
void AMediaExtractor_readSampleData(void) { ATL_NDK_STUB_BODY(179); }
void AMediaExtractor_seekTo(void) { ATL_NDK_STUB_BODY(180); }
void AMediaExtractor_selectTrack(void) { ATL_NDK_STUB_BODY(181); }
void AMediaExtractor_setDataSource(void) { ATL_NDK_STUB_BODY(182); }
void AMediaExtractor_setDataSourceCustom(void) { ATL_NDK_STUB_BODY(183); }
void AMediaExtractor_setDataSourceFd(void) { ATL_NDK_STUB_BODY(184); }
void AMediaExtractor_unselectTrack(void) { ATL_NDK_STUB_BODY(185); }
void AMediaFormat_clear(void) { ATL_NDK_STUB_BODY(186); }
void AMediaFormat_copy(void) { ATL_NDK_STUB_BODY(187); }
void AMediaFormat_getDouble(void) { ATL_NDK_STUB_BODY(188); }
void AMediaFormat_getRect(void) { ATL_NDK_STUB_BODY(189); }
void AMediaFormat_getSize(void) { ATL_NDK_STUB_BODY(190); }
void AMediaFormat_setDouble(void) { ATL_NDK_STUB_BODY(191); }
void AMediaFormat_setRect(void) { ATL_NDK_STUB_BODY(192); }
void AMediaFormat_setSize(void) { ATL_NDK_STUB_BODY(193); }
void AMediaMuxer_addTrack(void) { ATL_NDK_STUB_BODY(194); }
void AMediaMuxer_append(void) { ATL_NDK_STUB_BODY(195); }
void AMediaMuxer_delete(void) { ATL_NDK_STUB_BODY(196); }
void AMediaMuxer_getTrackCount(void) { ATL_NDK_STUB_BODY(197); }
void AMediaMuxer_getTrackFormat(void) { ATL_NDK_STUB_BODY(198); }
void AMediaMuxer_new(void) { ATL_NDK_STUB_BODY(199); }
void AMediaMuxer_setLocation(void) { ATL_NDK_STUB_BODY(200); }
void AMediaMuxer_setOrientationHint(void) { ATL_NDK_STUB_BODY(201); }
void AMediaMuxer_start(void) { ATL_NDK_STUB_BODY(202); }
void AMediaMuxer_stop(void) { ATL_NDK_STUB_BODY(203); }
void AMediaMuxer_writeSampleData(void) { ATL_NDK_STUB_BODY(204); }
void AMotionEvent_fromJava(void) { ATL_NDK_STUB_BODY(205); }
void AMotionEvent_getActionButton(void) { ATL_NDK_STUB_BODY(206); }
void AMotionEvent_getButtonState(void) { ATL_NDK_STUB_BODY(207); }
void AMotionEvent_getClassification(void) { ATL_NDK_STUB_BODY(208); }
void AMotionEvent_getDownTime(void) { ATL_NDK_STUB_BODY(209); }
void AMotionEvent_getEdgeFlags(void) { ATL_NDK_STUB_BODY(210); }
void AMotionEvent_getEventTime(void) { ATL_NDK_STUB_BODY(211); }
void AMotionEvent_getFlags(void) { ATL_NDK_STUB_BODY(212); }
void AMotionEvent_getHistoricalAxisValue(void) { ATL_NDK_STUB_BODY(213); }
void AMotionEvent_getHistoricalEventTime(void) { ATL_NDK_STUB_BODY(214); }
void AMotionEvent_getHistoricalOrientation(void) { ATL_NDK_STUB_BODY(215); }
void AMotionEvent_getHistoricalPressure(void) { ATL_NDK_STUB_BODY(216); }
void AMotionEvent_getHistoricalRawX(void) { ATL_NDK_STUB_BODY(217); }
void AMotionEvent_getHistoricalRawY(void) { ATL_NDK_STUB_BODY(218); }
void AMotionEvent_getHistoricalSize(void) { ATL_NDK_STUB_BODY(219); }
void AMotionEvent_getHistoricalToolMajor(void) { ATL_NDK_STUB_BODY(220); }
void AMotionEvent_getHistoricalToolMinor(void) { ATL_NDK_STUB_BODY(221); }
void AMotionEvent_getHistoricalTouchMajor(void) { ATL_NDK_STUB_BODY(222); }
void AMotionEvent_getHistoricalTouchMinor(void) { ATL_NDK_STUB_BODY(223); }
void AMotionEvent_getHistoricalX(void) { ATL_NDK_STUB_BODY(224); }
void AMotionEvent_getHistoricalY(void) { ATL_NDK_STUB_BODY(225); }
void AMotionEvent_getHistorySize(void) { ATL_NDK_STUB_BODY(226); }
void AMotionEvent_getMetaState(void) { ATL_NDK_STUB_BODY(227); }
void AMotionEvent_getOrientation(void) { ATL_NDK_STUB_BODY(228); }
void AMotionEvent_getPressure(void) { ATL_NDK_STUB_BODY(229); }
void AMotionEvent_getRawX(void) { ATL_NDK_STUB_BODY(230); }
void AMotionEvent_getRawY(void) { ATL_NDK_STUB_BODY(231); }
void AMotionEvent_getSize(void) { ATL_NDK_STUB_BODY(232); }
void AMotionEvent_getToolMajor(void) { ATL_NDK_STUB_BODY(233); }
void AMotionEvent_getToolMinor(void) { ATL_NDK_STUB_BODY(234); }
void AMotionEvent_getToolType(void) { ATL_NDK_STUB_BODY(235); }
void AMotionEvent_getTouchMajor(void) { ATL_NDK_STUB_BODY(236); }
void AMotionEvent_getTouchMinor(void) { ATL_NDK_STUB_BODY(237); }
void AMotionEvent_getXOffset(void) { ATL_NDK_STUB_BODY(238); }
void AMotionEvent_getXPrecision(void) { ATL_NDK_STUB_BODY(239); }
void AMotionEvent_getYOffset(void) { ATL_NDK_STUB_BODY(240); }
void AMotionEvent_getYPrecision(void) { ATL_NDK_STUB_BODY(241); }
void ANativeWindow_getBuffersDataSpace(void) { ATL_NDK_STUB_BODY(242); }
void ANativeWindow_setBuffersDataSpace(void) { ATL_NDK_STUB_BODY(243); }
void ANativeWindow_toSurface(void) { ATL_NDK_STUB_BODY(244); }
void ANativeWindow_tryAllocateBuffers(void) { ATL_NDK_STUB_BODY(245); }
void AndroidBitmap_compress(void) { ATL_NDK_STUB_BODY(246); }
void AndroidBitmap_getDataSpace(void) { ATL_NDK_STUB_BODY(247); }
void AndroidBitmap_getHardwareBuffer(void) { ATL_NDK_STUB_BODY(248); }
void APerformanceHint_closeSession(void) { ATL_NDK_STUB_BODY(249); }
void APerformanceHint_createSession(void) { ATL_NDK_STUB_BODY(250); }
void APerformanceHint_getManager(void) { ATL_NDK_STUB_BODY(251); }
void APerformanceHint_getPreferredUpdateRateNanos(void) { ATL_NDK_STUB_BODY(252); }
void APerformanceHint_reportActualWorkDuration(void) { ATL_NDK_STUB_BODY(253); }
void APerformanceHint_updateTargetWorkDuration(void) { ATL_NDK_STUB_BODY(254); }
void ASharedMemory_create(void) { ATL_NDK_STUB_BODY(255); }
void ASharedMemory_getSize(void) { ATL_NDK_STUB_BODY(256); }
void ASharedMemory_setProt(void) { ATL_NDK_STUB_BODY(257); }
void ASurfaceTexture_acquireANativeWindow(void) { ATL_NDK_STUB_BODY(258); }
void ASurfaceTexture_attachToGLContext(void) { ATL_NDK_STUB_BODY(259); }
void ASurfaceTexture_detachFromGLContext(void) { ATL_NDK_STUB_BODY(260); }
void ASurfaceTexture_fromSurfaceTexture(void) { ATL_NDK_STUB_BODY(261); }
void ASurfaceTexture_getTimestamp(void) { ATL_NDK_STUB_BODY(262); }
void ASurfaceTexture_getTransformMatrix(void) { ATL_NDK_STUB_BODY(263); }
void ASurfaceTexture_release(void) { ATL_NDK_STUB_BODY(264); }
void ASurfaceTexture_updateTexImage(void) { ATL_NDK_STUB_BODY(265); }
void ASystemFont_close(void) { ATL_NDK_STUB_BODY(266); }
void ASystemFont_getAxisCount(void) { ATL_NDK_STUB_BODY(267); }
void ASystemFont_getAxisTag(void) { ATL_NDK_STUB_BODY(268); }
void ASystemFont_getAxisValue(void) { ATL_NDK_STUB_BODY(269); }
void ASystemFont_getCollectionINdex(void) { ATL_NDK_STUB_BODY(270); }
void ASystemFont_getFontFilePath(void) { ATL_NDK_STUB_BODY(271); }
void ASystemFont_getLocale(void) { ATL_NDK_STUB_BODY(272); }
void ASystemFont_getWeight(void) { ATL_NDK_STUB_BODY(273); }
void ASystemFont_isItalic(void) { ATL_NDK_STUB_BODY(274); }
void ASystemFontIterator_close(void) { ATL_NDK_STUB_BODY(275); }
void ASystemFontIterator_next(void) { ATL_NDK_STUB_BODY(276); }
void ASystemFontIterator_open(void) { ATL_NDK_STUB_BODY(277); }
void ATrace_beginAsyncSection(void) { ATL_NDK_STUB_BODY(278); }
void ATrace_beginSection(void) { ATL_NDK_STUB_BODY(279); }
void ATrace_endAsyncSection(void) { ATL_NDK_STUB_BODY(280); }
void ATrace_endSection(void) { ATL_NDK_STUB_BODY(281); }
void ATrace_setCounter(void) { ATL_NDK_STUB_BODY(282); }
int android_get_device_api_level(void) { return 30; }
