#!/bin/bash
# Regenerate the route-B NDK link shim.
#
# Compiling against the NDK headers is only half of B4: libxul also has to
# *link*.  On Android the NDK sysroot supplies liblog, libandroid, libmediandk
# and libjnigraphics; here they have to be assembled by hand.  This directory
# is handed to the linker with -L (see mozconfig-route-b).
#
#   liblog.so        a forwarder: dlsym the runtime's __android_log_vprint,
#                    stderr if it is not there.  Linking ART's own liblog does
#                    not work -- it needs a newer glibc than Gecko's bootstrap
#                    sysroot has, so the link fails on __isoc23_strtol.
#   libandroid.so    ATL's own libandroid.so.0, plus the stub library
#   libjnigraphics.so  ATL puts AndroidBitmap_* in libandroid
#   libmediandk.so   entirely stubs: ATL has no MediaCodec/MediaDrm NDK
#   libatlndkstub.so recording stubs for every NDK entry point Gecko references
#                    that nothing on this system defines
#
# The stub library is the honest measure of the runtime gap: each symbol in
# ndk-gap.txt is an NDK entry point ATL would have to grow before the code
# path that calls it can run.
#
# Each stub logs itself (stderr + ATL_NDK_STUB_LOG) and then aborts, or with
# ATL_NDK_STUB_SOFT=1 returns zero and keeps going so one run enumerates the
# whole startup path.  See ndk-stub-runtime.c for the environment variables.

set -euo pipefail
cd "$(dirname "$0")"

# OUTDIR writes the generated half somewhere else, so a second architecture
# gets its own outputs without a second copy of these sources. Inputs are
# always read from this directory.
OUTDIR=${OUTDIR:-.}
mkdir -p "$OUTDIR"

SHIM_HEADERS=${SHIM_HEADERS:-../android-headers-shim}
# The translation layer's own libandroid, of the architecture being built for.
# No default: linking libxul against the wrong one is a silent gap-list change,
# so the caller has to say which build it means.  gecko/README.md says where the
# arm64 one comes from.
: "${ATL_LIBANDROID:?set ATL_LIBANDROID (atlas libandroid.so.0 for this target)}"
CC=${CC:-$HOME/.mozbuild/clang/bin/clang}
# Same sysroot Gecko itself builds against: the host's glibc is newer, and
# linking a library that references its symbol versions fails at libxul time.
SYSROOT=${SYSROOT:-$HOME/.mozbuild/sysroot-x86_64-linux-gnu}
CFLAGS_SHIM="--sysroot=$SYSROOT -shared -fPIC"
# -fno-stack-protector is load-bearing: the stubs write their zero return value
# straight into the return registers, and the stack-guard epilogue clobbers rax.
CFLAGS_STUB="-O1 -fno-stack-protector -fasynchronous-unwind-tables"
# Where a stub run writes its trace when ATL_NDK_STUB_LOG is unset.
STUB_LOG_DEFAULT=${ATL_NDK_STUB_LOG_DEFAULT:-/tmp/atl-ndk-stub-trace.log}

[ -e "$ATL_LIBANDROID" ] || { echo "no ATL libandroid at $ATL_LIBANDROID" >&2; exit 1; }

# Every A*/AndroidBitmap_* entry point declared by the shim headers.
grep -ho '\b\(A[A-Z][A-Za-z]*\|AndroidBitmap\)_[A-Za-z0-9_]*\s*(' \
	"$SHIM_HEADERS"/ndk/android/*.h "$SHIM_HEADERS"/ndk/media/*.h \
	"$SHIM_HEADERS"/android/native_window_jni.h \
	| sed 's/[[:space:]]*($//; s/($//' | sort -u > /tmp/.ndk-decls.$$

# Minus whatever ATL's own libandroid already defines.
nm -D --defined-only "$ATL_LIBANDROID" \
	| awk '$2 ~ /^[TWBDR]$/ {print $3}' | sort -u > /tmp/.ndk-have.$$

comm -23 /tmp/.ndk-decls.$$ /tmp/.ndk-have.$$ > "$OUTDIR/ndk-gap.txt"
# Bionic entry points that do not follow the A<Thing>_ naming.
echo ASharedMemory_create >> "$OUTDIR/ndk-gap.txt"
sort -u -o "$OUTDIR/ndk-gap.txt" "$OUTDIR/ndk-gap.txt"
rm -f /tmp/.ndk-decls.$$ /tmp/.ndk-have.$$

{
	echo '/* Generated by regenerate.sh -- do not edit. */'
	echo '#include "ndk-stub-runtime.h"'
	echo ''
	echo 'struct atl_ndk_stub atl_ndk_stub_table[] = {'
	while read -r sym; do
		[ -n "$sym" ] || continue
		echo "  { \"$sym\", 0 },"
	done < "$OUTDIR/ndk-gap.txt"
	echo '};'
	echo 'const unsigned atl_ndk_stub_count ='
	echo '    sizeof(atl_ndk_stub_table) / sizeof(atl_ndk_stub_table[0]);'
	echo ''
	# Every stub keeps the void(void) shape it linked with: the soft-mode
	# return value is written into the return registers by hand.
	i=0
	while read -r sym; do
		[ -n "$sym" ] || continue
		echo "void $sym(void) { ATL_NDK_STUB_BODY($i); }"
		i=$((i + 1))
	done < "$OUTDIR/ndk-gap.txt"
	# A query, not an operation: answering it is better than aborting.
	echo 'int android_get_device_api_level(void) { return 30; }'
} > "$OUTDIR/ndk-stubs.c"

$CC $CFLAGS_SHIM $CFLAGS_STUB -I. -Wl,-soname,libatlndkstub.so \
	-DATL_NDK_STUB_DEFAULT_LOG="\"$STUB_LOG_DEFAULT\"" \
	-o "$OUTDIR/libatlndkstub.so" "$OUTDIR/ndk-stubs.c" ndk-stub-runtime.c

$CC $CFLAGS_SHIM -Wl,-soname,liblog.so -o "$OUTDIR/liblog.so" log-forward.c -ldl
cat > "$OUTDIR/libandroid.so" <<EOF
/* GNU ld script: ATL's libandroid, plus stubs for what it does not have. */
INPUT ( $ATL_LIBANDROID libatlndkstub.so )
EOF
cat > "$OUTDIR/libjnigraphics.so" <<EOF
/* GNU ld script: ATL keeps AndroidBitmap_* in libandroid. */
INPUT ( $ATL_LIBANDROID libatlndkstub.so )
EOF
cat > "$OUTDIR/libmediandk.so" <<'EOF'
/* GNU ld script: ATL implements none of libmediandk. */
INPUT ( libatlndkstub.so )
EOF

echo "stubbed $(wc -l < "$OUTDIR/ndk-gap.txt") NDK entry points"
