/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_MEDIA_NDKIMAGEREADER_H
#define ATL_SHIM_MEDIA_NDKIMAGEREADER_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/media/NdkImageReader.h"
ATL_NDK_VISIBILITY_POP
#endif
