/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_MEDIA_NDKMEDIADATASOURCE_H
#define ATL_SHIM_MEDIA_NDKMEDIADATASOURCE_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/media/NdkMediaDataSource.h"
ATL_NDK_VISIBILITY_POP
#endif
