/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_MEDIA_NDKMEDIAFORMAT_H
#define ATL_SHIM_MEDIA_NDKMEDIAFORMAT_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/media/NdkMediaFormat.h"
ATL_NDK_VISIBILITY_POP
#endif
