#!/bin/bash
# Write the meson cross file for the aarch64 build. Regenerated on every run, so
# a toolchain change can never leave a stale file behind.
#
#   CC CXX AR STRIP PKG_CONFIG        the cross toolchain
#   HOST_JAVA_HOME TARGET_JAVA_HOME   host javac, target jni.h + libjvm.so
#   CROSS_LIB_DIRS CROSS_INCLUDE_DIRS space-separated, the staged sysroot
#
# Usage: write-meson-cross.sh PATH
set -euo pipefail

out="${1:?usage: write-meson-cross.sh PATH}"
: "${CC:?}" "${CXX:?}" "${HOST_JAVA_HOME:?}" "${TARGET_JAVA_HOME:?}"

# In a cross build meson ignores CFLAGS/LDFLAGS and LIBRARY_PATH for the host
# machine -- the cross file is the only way in, and cc.find_library() then finds
# the staged prefix too.
lib_args=""; for d in ${CROSS_LIB_DIRS:-};     do lib_args="$lib_args'-L$d', "; done
inc_args=""; for d in ${CROSS_INCLUDE_DIRS:-}; do inc_args="$inc_args'-I$d', "; done

mkdir -p "$(dirname "$out")"
cat >"$out" <<INI
# Generated by scripts/write-meson-cross.sh -- do not edit.

[binaries]
c = '$CC'
cpp = '$CXX'
ar = '${AR:-aarch64-linux-gnu-ar}'
strip = '${STRIP:-aarch64-linux-gnu-strip}'
pkg-config = '${PKG_CONFIG:-aarch64-linux-gnu-pkg-config}'
# The Java compiler stays a host tool whatever the target is: bytecode is
# bytecode. meson's binary key for it is 'java', and it wants javac, not java --
# a 'javac' key is silently ignored and the build then fails with
# "Unknown compiler: .../bin/java".
java = '$HOST_JAVA_HOME/bin/javac'

[properties]
# What meson's 'jni' dependency resolves jni.h and libjvm.so from. It must be
# the *target* JDK, or the launcher would link against the host's libjvm.
java_home = '$TARGET_JAVA_HOME'

[built-in options]
c_args = [$inc_args]
cpp_args = [$inc_args]
c_link_args = [$lib_args]
cpp_link_args = [$lib_args]

[host_machine]
system = 'linux'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
INI
echo "wrote $out"
