#!/bin/bash
# Regenerate the NDK header shim -- the --with-android-headers input of
# mozconfig-atl-glibc[-arm64].
#
# Gecko's android-toolkit code includes <android/*.h>, <media/Ndk*.h> and the
# GLES headers, all of which come free from the NDK sysroot on a real Android
# build.  This build targets glibc, so they have to be put on the include path
# by hand.
#
# Layout:
#   ndk-shim.h      the __ANDROID_API__ / __INTRODUCED_IN prologue
#   ndk/            the real headers, off the include path
#   android/,media/ one-line wrappers: prologue, then the real header
#   GLES2/,GLES3/,KHR/  the host's Mesa headers, which is what ATL renders with
#
# The wrapper indirection exists so the prologue is only in force inside the
# NDK headers themselves.  Only these directories are exposed: the ATL header
# tree also carries linux/, system/ and cutils/, which would shadow the host's
# own kernel headers.
#
# ndk/ is committed as real files, not symlinks, so a checkout builds with no
# NDK installed.  Running this script is only needed to refresh them, and it
# needs all three sources below; see README.md for what each one is.

set -euo pipefail
cd "$(dirname "$0")"

# The three header sources.  No defaults: each one is a checkout or an install
# whose path is the caller's, and a wrong guess would silently mix API levels.
#
#   ATL_HEADERS   ubports android-headers, the "30" directory -- the bionic
#                 headers ATL itself implements against
#   NDK_HEADERS   an NDK sysroot's usr/include, for the android/*.h ATL's tree
#                 does not carry
#   NDK_SYSROOT   an NDK sysroot's usr/include, for media/Ndk*.h
#
# NDK_HEADERS and NDK_SYSROOT are separate because the committed tree was taken
# from two different NDKs; see README.md.
: "${ATL_HEADERS:?set ATL_HEADERS (ubports android-headers .../30)}"
: "${NDK_HEADERS:?set NDK_HEADERS (an NDK sysroot usr/include)}"
: "${NDK_SYSROOT:?set NDK_SYSROOT (an NDK sysroot usr/include)}"

rm -rf ndk android media GLES2 GLES3 KHR
mkdir -p ndk/android ndk/media android media

link_ndk() {  # <subdir> <source dir> <name...>  -- copies, see above
	local sub=$1 src=$2; shift 2
	for h in "$@"; do
		[ -e "$src/$h" ] || { echo "missing: $src/$h" >&2; exit 1; }
		cp "$src/$h" "ndk/$sub/$h"
	done
}

link_ndk android "$ATL_HEADERS/android" \
	api-level.h data_space.h dlext.h hardware_buffer.h hdr_metadata.h \
	log.h native_window.h rect.h set_abort_message.h

# Not in ATL's tree: the NDK's own copies.
link_ndk android "$NDK_HEADERS/android" \
	bitmap.h choreographer.h font.h font_matcher.h imagedecoder.h input.h \
	keycodes.h looper.h performance_hint.h sharedmem.h surface_texture.h \
	surface_texture_jni.h system_fonts.h trace.h versioning.h

# ATL implements none of libmediandk, so take the NDK's own, which are newer
# and (unlike ATL's copies) parse as C.
link_ndk media "$NDK_SYSROOT/media" \
	NdkImage.h NdkImageReader.h NdkMediaCodec.h NdkMediaCrypto.h \
	NdkMediaDataSource.h NdkMediaDrm.h NdkMediaError.h NdkMediaExtractor.h \
	NdkMediaFormat.h NdkMediaMuxer.h

for real in ndk/*/*.h; do
	sub=$(basename "$(dirname "$real")")
	name=$(basename "$real")
	guard="ATL_SHIM_$(echo "${sub}_${name}" | tr 'a-z.\-/' 'A-Z___')"
	cat > "$sub/$name" <<EOF
/* Generated by regenerate.sh -- do not edit. */
#ifndef $guard
#define $guard
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/$sub/$name"
ATL_NDK_VISIBILITY_POP
#endif
EOF
done

# ANativeWindow_fromSurface and friends: no NDK copy carries the ATL variant.
cat > android/native_window_jni.h <<'EOF'
/* Route B: the NDK's <android/native_window_jni.h>, which ATL's header tree
 * does not carry.  ATL implements these in libandroid.so.0. */
#ifndef ATL_SHIM_ANDROID_NATIVE_WINDOW_JNI_H
#define ATL_SHIM_ANDROID_NATIVE_WINDOW_JNI_H

#include <android/native_window.h>
#include <jni.h>

#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH

#ifdef __cplusplus
extern "C" {
#endif

ANativeWindow* ANativeWindow_fromSurface(JNIEnv* env, jobject surface);
ANativeWindow* ANativeWindow_fromSurfaceTexture(JNIEnv* env, jobject surfaceTexture);
jobject ANativeWindow_toSurface(JNIEnv* env, ANativeWindow* window);

#ifdef __cplusplus
}
#endif

ATL_NDK_VISIBILITY_POP

#endif
EOF

# The GL headers: Mesa's, since that is what ATL draws through off-device.
for d in GLES2 GLES3 KHR; do
	ln -sfn "/usr/include/$d" "$d"
done

echo "shim regenerated: $(ls ndk/android | wc -l) android, $(ls ndk/media | wc -l) media headers"
