/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_API_LEVEL_H
#define ATL_SHIM_ANDROID_API_LEVEL_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/api-level.h"
ATL_NDK_VISIBILITY_POP
#endif
