/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_CHOREOGRAPHER_H
#define ATL_SHIM_ANDROID_CHOREOGRAPHER_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/choreographer.h"
ATL_NDK_VISIBILITY_POP
#endif
