/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_DATA_SPACE_H
#define ATL_SHIM_ANDROID_DATA_SPACE_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/data_space.h"
ATL_NDK_VISIBILITY_POP
#endif
