/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_FONT_MATCHER_H
#define ATL_SHIM_ANDROID_FONT_MATCHER_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/font_matcher.h"
ATL_NDK_VISIBILITY_POP
#endif
