/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_HARDWARE_BUFFER_H
#define ATL_SHIM_ANDROID_HARDWARE_BUFFER_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/hardware_buffer.h"
ATL_NDK_VISIBILITY_POP
#endif
