/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_HDR_METADATA_H
#define ATL_SHIM_ANDROID_HDR_METADATA_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/hdr_metadata.h"
ATL_NDK_VISIBILITY_POP
#endif
