/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_LOOPER_H
#define ATL_SHIM_ANDROID_LOOPER_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/looper.h"
ATL_NDK_VISIBILITY_POP
#endif
