/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_NATIVE_WINDOW_H
#define ATL_SHIM_ANDROID_NATIVE_WINDOW_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/native_window.h"
ATL_NDK_VISIBILITY_POP
#endif
