/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_PERFORMANCE_HINT_H
#define ATL_SHIM_ANDROID_PERFORMANCE_HINT_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/performance_hint.h"
ATL_NDK_VISIBILITY_POP
#endif
