/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_SET_ABORT_MESSAGE_H
#define ATL_SHIM_ANDROID_SET_ABORT_MESSAGE_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/set_abort_message.h"
ATL_NDK_VISIBILITY_POP
#endif
