/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_SURFACE_TEXTURE_H
#define ATL_SHIM_ANDROID_SURFACE_TEXTURE_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/surface_texture.h"
ATL_NDK_VISIBILITY_POP
#endif
