/* Generated by regenerate.sh -- do not edit. */
#ifndef ATL_SHIM_ANDROID_SYSTEM_FONTS_H
#define ATL_SHIM_ANDROID_SYSTEM_FONTS_H
#include "../ndk-shim.h"
ATL_NDK_VISIBILITY_PUSH
#include "../ndk/android/system_fonts.h"
ATL_NDK_VISIBILITY_POP
#endif
